(()=>{
  const C=window.CRYPTO_HUB_CONFIG;
  const $=(s,r=document)=>r.querySelector(s), $$=(s,r=document)=>[...r.querySelectorAll(s)];
  const mode=()=>localStorage.getItem(C.networkModeKey)||C.defaultNetworkMode;
  const setMode=m=>{
    C.networks=C.networkProfiles[m]||C.networkProfiles.testnet;
    const label=$('#networkModeLabel'), button=$('#toggleMainnet');
    if(label)label.textContent=m==='mainnet'?'وضع Mainnet':'وضع Testnet';
    if(button)button.textContent=m==='mainnet'?'العودة إلى Testnet':'تفعيل Mainnet';
  };
  setMode(mode());
  let wallet=null,pending='',activeTab='earn',balanceTimer=null;
  const toast=m=>{const t=$('#toast');if(!t)return;t.textContent=m;t.classList.add('show');clearTimeout(window.__t);window.__t=setTimeout(()=>t.classList.remove('show'),3000)};
  const bytesB64=b=>btoa(String.fromCharCode(...new Uint8Array(b))), b64Bytes=s=>Uint8Array.from(atob(s),c=>c.charCodeAt(0));
  async function key(p,s){const b=await crypto.subtle.importKey('raw',new TextEncoder().encode(p),'PBKDF2',false,['deriveKey']);return crypto.subtle.deriveKey({name:'PBKDF2',salt:s,iterations:250000,hash:'SHA-256'},b,{name:'AES-GCM',length:256},false,['encrypt','decrypt'])}
  async function enc(text,p){const s=crypto.getRandomValues(new Uint8Array(16)),iv=crypto.getRandomValues(new Uint8Array(12)),k=await key(p,s),d=await crypto.subtle.encrypt({name:'AES-GCM',iv},k,new TextEncoder().encode(text));return{salt:bytesB64(s),iv:bytesB64(iv),data:bytesB64(d)}}
  async function dec(box,p){const k=await key(p,b64Bytes(box.salt)),d=await crypto.subtle.decrypt({name:'AES-GCM',iv:b64Bytes(box.iv)},k,b64Bytes(box.data));return new TextDecoder().decode(d)}
  const navTab=t=>{activeTab=t;$$('.tab-pane').forEach(x=>x.classList.add('hidden'));$(`#tab-${t}`).classList.remove('hidden');$$('.nav-item[data-tab]').forEach(x=>x.classList.toggle('active',x.dataset.tab===t));$('#pageTitle').textContent={earn:'الكسب والإحالات',wallet:'المحفظة اللامركزية',swap:'التداول والتبادل'}[t];$$('.subpage').forEach(x=>x.classList.add('hidden'));$('#sidebar').classList.remove('open');if(t==='wallet'&&wallet)refreshBalances()};
  const navPage=p=>{$$('.tab-pane').forEach(x=>x.classList.add('hidden'));$$('.subpage').forEach(x=>x.classList.add('hidden'));$(`#page-${p}`).classList.remove('hidden');$('#pageTitle').textContent=p==='wallet-assets'?'الأصول والشبكات':'الأمان والنسخ';$('#sidebar').classList.remove('open')};
  const renderEarn=()=>{
    const host=$('#earnList'); if(!host)return;
    host.innerHTML=C.earnSites.map(s=>{
      const ref=C.referralLinks[s.referralKey]||'';
      const target=ref&&!ref.startsWith('YOUR_')?ref:s.url;
      return`<article class="site-card"><div class="site-card-top"><span class="site-logo ${s.color}">${s.symbol}</span><span class="site-type">${s.tag}</span></div><h3>${s.name}</h3><p>${s.description}</p><div class="site-meta"><span>◉ رابط مباشر</span><span>↗ ${ref&&!ref.startsWith('YOUR_')?'إحالة مفعلة':'الرابط المباشر'}</span></div><a class="primary-btn earn-link" href="${target}" target="_blank" rel="noopener noreferrer">${ref&&!ref.startsWith('YOUR_')?'التسجيل عبر رابط الإحالة':'فتح الموقع'} ↗</a></article>`
    }).join('');
  };
  async function makeWallet(m){const evm=ethers.HDNodeWallet.fromPhrase(m),seedHex=ethers.Mnemonic.fromPhrase(m).computeSeed();let tron='غير متاح',derived=null;try{if(window.TronWeb)tron=TronWeb.address.fromPrivateKey(evm.privateKey.slice(2))}catch(e){console.warn('TRON derivation unavailable',e)}try{derived=window.chainReady?await window.chainReady(seedHex):null}catch(e){console.warn('BTC/SOL derivation unavailable',e)}return{mnemonic:m,evm:{address:evm.address,privateKey:evm.privateKey},tron,bitcoin:derived?.bitcoin||'غير متاح',solana:derived?.solana||'غير متاح'}}
  const setWallet=unlocked=>{$('#vaultState').textContent=unlocked?'مفتوحة محلياً':'محفظة مقفلة';$('#walletStatus').textContent=unlocked?'مفتوحة محلياً':'مقفلة';$('#unlockBanner').classList.toggle('hidden',unlocked);$('#evmAddress').textContent=unlocked?wallet.evm.address:'أنشئ أو استورد محفظة';renderAssets();if(unlocked)refreshBalances();else{clearInterval(balanceTimer);balanceTimer=null}};
  const asset=(n,s,a,b='—')=>`<article class="asset-card"><div class="asset-top"><span class="coin ${n.toLowerCase().replaceAll(' ','-')}">${s[0]}</span><span class="chain-name">${n}</span><i class="asset-status"></i></div><strong class="asset-balance">${b} ${s}</strong><code>${a||'افتح المحفظة'}</code><button class="text-btn copy-address" data-address="${a||''}">نسخ العنوان ⧉</button></article>`;
  const renderAssets=()=>{const e=wallet?.evm?.address||'',t=wallet?.tron||'',s=wallet?.solana||'',btc=wallet?.bitcoin||'';const h=[asset('Ethereum','ETH',e),asset('BNB Chain','BNB',e),asset('Polygon','POL',e),asset('Arbitrum','ETH',e),asset('Avalanche','AVAX',e),asset('TRON · TRX','TRX',t),asset('USDT · TRC20','USDT',t),asset('Bitcoin','BTC',btc),asset('Solana','SOL',s)].join('');$('#dashboardAssets').innerHTML=h;$('#assetList').innerHTML=h;$$('.copy-address').forEach(b=>b.onclick=()=>copy(b.dataset.address))};
  async function copy(v){if(!v||v.includes('افتح')||v.includes('متاح لاحقاً'))return toast('لا يوجد عنوان قابل للنسخ بعد');try{await navigator.clipboard.writeText(v);toast('تم نسخ العنوان')}catch{toast(v)}}
  async function refreshBalances(){if(!wallet?.evm?.address)return;const addr=wallet.evm.address;const networks=Object.entries(C.networks||{}).filter(([,n])=>n.rpcUrl&&n.chainId);const results=await Promise.all(networks.map(async([key,n])=>{try{const c=new AbortController(),timer=setTimeout(()=>c.abort(),8000),r=await fetch(n.rpcUrl,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({jsonrpc:'2.0',id:1,method:'eth_getBalance',params:[addr,'latest']}),signal:c.signal});clearTimeout(timer);const j=await r.json();return[key,j.result?Number(BigInt(j.result))/1e18:null]}catch{return[key,null]}}));const values=Object.fromEntries(results);const extra=await Promise.all([fetch(`${C.networks.bitcoin.apiBase}/address/${wallet.bitcoin}`,{signal:AbortSignal.timeout(8000)}).then(r=>r.json()).then(j=>['bitcoin',(j.chain_stats.funded_txo_sum-j.chain_stats.spent_txo_sum)/1e8]).catch(()=>['bitcoin',null]),fetch(C.networks.solana.rpcUrl,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({jsonrpc:'2.0',id:1,method:'getBalance',params:[wallet.solana]}),signal:AbortSignal.timeout(8000)}).then(r=>r.json()).then(j=>['solana',j.result?.value/1e9]).catch(()=>['solana',null]),fetch(`${C.networks.tron.rpcUrl}/v1/accounts/${wallet.tron}`,{signal:AbortSignal.timeout(8000)}).then(r=>r.json()).then(j=>['tron',(j.data?.[0]?.balance||0)/1e6]).catch(()=>['tron',null])]);extra.forEach(([k,v])=>values[k]=v);$$('.asset-card').forEach(card=>{const name=card.querySelector('.chain-name')?.textContent||'',key=Object.keys(C.networks).find(k=>C.networks[k].name===name||name.startsWith(C.networks[k].name+' ·'));if(key&&values[key]!=null){const b=card.querySelector('.asset-balance');if(b)b.textContent=`${values[key].toFixed(6)} ${C.networks[key].symbol}`}});if(wallet)balanceTimer=setTimeout(()=>refreshBalances(),60000)}
  async function create(m){try{if(!ethers.Mnemonic.isValidMnemonic(m))throw Error('عبارة BIP39 غير صحيحة');pending=m;$('#mnemonicWords').textContent=m;$('#mnemonicPanel').classList.remove('hidden');$('#lockedPanel').classList.add('hidden');toast('راجع الكلمات ثم شفّرها محلياً')}catch(e){toast(e.message)}}
  $('#generateWallet').onclick=()=>create(ethers.Mnemonic.entropyToPhrase(ethers.randomBytes(16)));$('#importWallet').onclick=()=>create($('#importPhrase').value.trim().replace(/\s+/g,' '));
  $('#saveVault').onclick=async()=>{try{const p=$('#vaultPassword').value;if(p.length<8)return toast('كلمة المرور 8 أحرف على الأقل');localStorage.setItem(C.storageKey,JSON.stringify(await enc(pending,p)));wallet=await makeWallet(pending);setWallet(true);$('#mnemonicPanel').classList.add('hidden');toast('تم التشفير والحفظ محلياً')}catch(e){toast('تعذر حفظ المحفظة محلياً')}};
  $('#unlockVault').onclick=async()=>{try{const raw=localStorage.getItem(C.storageKey);if(!raw)throw Error();wallet=await makeWallet(await dec(JSON.parse(raw),$('#unlockPassword').value));setWallet(true);toast('تم فتح المحفظة')}catch{toast('كلمة المرور غير صحيحة أو لا توجد محفظة')}};
  $('#toggleMainnet').onclick=()=>{if(mode()==='mainnet'){localStorage.setItem(C.networkModeKey,'testnet');setMode('testnet');toast('تمت العودة إلى Testnet')}else{const phrase=prompt('للتفعيل اكتب MAINNET. لن يتم إرسال أي معاملة تلقائيًا:');if(phrase==='MAINNET'){localStorage.setItem(C.networkModeKey,'mainnet');setMode('mainnet');toast('تم تفعيل Mainnet للقراءة والتوقيع اليدوي فقط')}else toast('لم يتم تفعيل Mainnet')}};$('#lockWallet').onclick=()=>{wallet=null;setWallet(false);toast('تم قفل المحفظة ومسح المفاتيح من الذاكرة')};$('#copyEvm').onclick=()=>copy(wallet?.evm?.address||'');
  $('#getQuote').onclick=()=>{if(!wallet)return toast('افتح المحفظة أولاً');if(!$('#swapAmount').value)return toast('أدخل المبلغ أولاً');$('#swapQuote').value='يتم جلب العرض...';setTimeout(()=>{$('#swapQuote').value='عرض تجريبي فقط';$('#swapStatus').textContent='لا يتم تنفيذ أو توقيع أي معاملة';toast('هذا العرض غير قابل للتنفيذ حتى يكتمل تكامل DEX الآمن')},600)};
  $('#flipSwap').onclick=()=>{const a=$('#swapFrom'),b=$('#swapTo'),x=a.value;a.value=b.value;b.value=x};$$('[data-tab]').forEach(b=>b.onclick=()=>navTab(b.dataset.tab));$$('[data-page]').forEach(b=>b.onclick=()=>navPage(b.dataset.page));$('[data-scroll]').onclick=()=>document.getElementById('earnSites').scrollIntoView({behavior:'smooth'});$('#mobileMenu').onclick=()=>$('#sidebar').classList.toggle('open');renderEarn();renderAssets();setWallet(false);if(localStorage.getItem(C.storageKey))$('#unlockBanner p').textContent='توجد محفظة مشفرة على هذا الجهاز. افتحها من قسم الأمان.';
})();
